accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('password_change/', views.password_change, name='password_change'),
    path('edit/', views.profile_edit, name='profile_edit'),

    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),
]

instagramsns/urls.py
from django.urls import path, re_path

from . import views

app_name = 'instagramsns'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like', views.post_like, name='post_like'),
    path('post/<int:pk>/dislike', views.post_dislike, name='post_dislike'),
    path('post/<int:post_pk>/comment/new', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

instagramsns/models.py
import re
from accounts.models import settings
from django.urls import reverse
from django.db import models

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

# user
# -> Post.objects.filter(author=user)
# -> user.post_set.all()
# related_name은 DB 스키마와는 상관없지만 djangoORM과 상관이 있다.

class Post(BaseModel): 
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='my_post_set', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='instagramsns/post/%Y/%m/%d')
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='like_post_set')

    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        tag_name_list = re.findall(r'#([a-zA-Z\dㄱ-힣]+)', self.caption)
        tag_list = []                                           # list 형식
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)   # (object, created) 튜플 형식 반환
            tag_list.append(tag)
        return tag_list

    def get_absolute_url(self):
        return reverse("instagramsns:post_detail", args=[self.pk])

    # 어떤 사용자가 어떤 포스팅에 대해 좋아요를 눌렀는지 확인할 함수
    # like_user_set에 존재하는 user면 True, 아니면 False
    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering =['-id']

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Comment(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        ordering = ['-id']

instagramsns/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        widgets = {
            'caption': forms.Textarea,
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={"rows": 2}),
        }

instagramsns/views.py
from django.contrib import messages 
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from .forms import PostForm, CommentForm
from .models import Tag, Post
from datetime import timedelta

@login_required
def index(request):
    timesince = timezone.now() - timedelta(days=3)
    post_list = Post.objects.all()\
        .filter(
            Q(author=request.user) |
            Q(author__in=request.user.following_set.all())
        )\
        .filter(
            created_at__gte = timesince # greater than equal
        )

    # User.objects.all() 은 유연하지 않은 방법
    suggested_user_list = get_user_model().objects.all()\
        .exclude(pk=request.user.pk)\
        .exclude(pk__in=request.user.following_set.all())[:5]

    comment_form = CommentForm()

    return render(request, "instagramsns/index.html", {
        "post_list": post_list,
        "suggested_user_list": suggested_user_list,
        "comment_form": comment_form,
    })

@login_required 
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # DB에 당장 저장하지 않는다
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())  # 리스트 형식이므로 * 붙여주기
            messages.success(request, "포스팅을 저장했습니다.")
            return redirect(post)   # get_absolute_url 활용
    else:
        form = PostForm()
    
    return render(request, 'instagramsns/post_form.html ', {
        "form": form,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    return render(request, "instagramsns/post_detail.html", {
        "post": post,
        "comment_form": comment_form,
    })

@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    messages.success(request, f"포스팅#{post.pk}를 좋아합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

@login_required
def post_dislike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, f"포스팅#{post.pk} 좋아요를 취소합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

def user_page(request, username):
    # urls.py에서 넘겨받은 username이 
    # logined된 User가 가진 필드에 존재하는가를 체크해야 한다.
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)  # is_active로 접근이 허용된 사람이 아니면 404
    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count() # 실제 DB에 count 쿼리를 던진다.
    #len(post_list)로 쓰면 post_list 전체를 다 가져와서 메모리에 얹은 다음에 메모리상의 리스트의 갯수를 반환해므로 느리다.
    
    if request.user.is_authenticated:   # 로그인이 되어 있다면 User 객체 리턴, 아닐시 AnonymousUser 객체 리턴
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    return render(request, "instagramsns/user_page.html",{
        "page_user": page_user,
        "post_list": post_list,
        "post_list_count": post_list_count,
        "is_follow": is_follow,
    })

@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # author와 와 post 에 대한 필드를 채우지 않았으므로
            # DB 저장을 지연시킨다.
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

            if request.is_ajax():
                return render(request, "instagramsns/_comment.html", {
                    "comment": comment,
                })
    
            return redirect(comment.post)
            
    else:
        form = CommentForm()
    return render(request, "instagramsns/comment_form.html", {
        "form": form,
    })

instagramsns/templates/instagramsns/_comment.html
{% load humanize %}

<div class="comment">
    <span style="font-size: 1em; font-weight: 500;">{{ comment.author }}</span>
    <span style="font-size: 0.85em;">{{ comment.message }}</span>
    <small class="text-muted">{{ comment.created_at|naturaltime}}</small>
</div>

instagramsns/templates/instagramsns/_post_card.html
{% load thumbnail %}
{% load bootstrap4 humanize instagramsns_tags %}

<div class="card">
    <div class="card-header">
        <img src="{{ post.author.avatar_url}}" class="rounded-circle mr-2" style="width: 32px; height: 32px;"/>
        <a href="{% url 'instagramsns:user_page' post.author.username %}" style="color: inherit;">
            <span style="font-size: 0.95rem;">{{ post.author.name }}</span>
        </a>
    </div>

    <div class="card-body">
        <img src="{% thumbnail post.photo 610x610 crop %}" alt="{{ post.caption }}" style="width: 100%; height: 100%;" />

        <div class="icon mt-3 mb-3">
            {% if post|is_like_user:user %}
                <a href="{% url 'instagramsns:post_dislike' post.pk %}">
                    <i class="far fa-heart fa-lg mr-2"></i>
                </a>
            {% else %}
                <a href="{% url 'instagramsns:post_like' post.pk %}">
                    <i class="fas fa-heart fa-lg mr-2"></i>
                </a>
            {% endif %}

            <i class="far fa-comment fa-flip-horizontal fa-lg mr-2"></i>
            <i class="far fa-eject fa-lg"></i>
        </div>

        <div id="post-{{ post.pk }}-comment-list" class="comment-list mb-1">
            {% for comment in post.comment_set.all.reverse %}
                {% include "instagramsns/_comment.html" %}
            {% endfor %}
        </div>

        <div class="tag mb-1">
            {% for tag in post.tag_set.all %}
                <span class="badge badge-light">
                    #{{ tag.name }}
                </span>
            {% endfor %}
        </div>
     
        <div class="createdat">
            <a href="{{ post.get_absolute_url }}" class="text-muted">
                <span style="font-size: 0.9rem;">
                    {{ post.created_at|naturaltime }}
                <span>
            </a>
        </div>
    </div>

    <div class="card-footer">
        <form id="post-{{ post.pk }}-comment-form" action="{% url 'instagramsns:comment_new' post.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" value="게시" class="btn btn-light btn-block">
        </form>

        <script>
        $(function() {
            var form_id = "post-{{ post.pk }}-comment-form";
            $("#" + form_id).submit(function(e) {
                e.preventDefault();

                var options = {
                    success: function(responseText, statusText, xhr, $form) {
                        console.group("ajaxSubmit response");
                        console.log(responseText);
                        console.log(statusText);
                        console.log(xhr);
                        console.log($form);
                        console.groupEnd();

                        $("#post-{{ post.pk }}-comment-list")
                        .append(
                            responseText
                        )
                    }
                };
                $(this).ajaxSubmit(options);
            });
            console.log("document ready.");
        });
        </script>
    </div>
</div>

instagramsns/templates/instagramsns/comment_form.html
{% extends "instagramsns/layout.html" %}

{% block content%}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include 'form.html' with form_title="댓글 쓰기" submit_label="댓글 쓰기" %}
            </div>
        </div>
    </div>
    
{% endblock %}

instagramsns/templates/instagramsns/index.html
{% extends "instagramsns/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-12">
                <a href="{% url 'instagramsns:post_new' %}" class="btn btn-dark">새 포스팅 쓰기</a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-7">
                {% for post in post_list %}
                    <div class="mb-4">
                        {% include "instagramsns/_post_card.html" %}
                    </div>
                {% empty %}
                    No Posting.
                {% endfor %}
            </div>
            <div class="col-sm-5">
                {% include "instagramsns/timeline_sidebar.html" %}
            </div>
        </div>
    </div>
{% endblock %}

instagramsns/templates/instagramsns/layout.html
{% extends "layout.html" %}

instagramsns/templates/instagramsns/post_detail.html
{% extends "instagramsns/layout.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "instagramsns/_post_card.html" %}
            </div>
        </div>
    </div>

{% endblock %}

instagramsns/templates/instagramsns/post_form.html
{% extends "instagramsns/layout.html" %}

{% block content%}

    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include 'form.html' with form_title="새 포스팅 쓰기" submit_label="새 포스팅 쓰기" %}
            </div>
        </div>
    </div>
    
{% endblock %}

instagramsns/templates/instagramsns/timeline_sidebar.html
<div class="d-flex p-2 mb-3">
    <div class= "mr-2">
        <img src="{{ user.avatar_url }}" style="width: 48px; height: 48px;" class="rounded-circle" />
    </div>
    <div>
        {{ user.username }}<br>
        <small class="text-muted">{{ user.name }}</small>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card-body">
        Stories from people you follow will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card-body">
        {% for suggested_user in suggested_user_list %}
            {% include "instagramsns/timeline_sidebar_user_follow.html" %}
        {% empty %}
            no recommendations.
        {% endfor %}
    </div>
</div>

instagramsns/templates/instagramsns/timeline_sidebar_user_follow.html
<div class="d-flex mb-2">
    <div class="mr-3">
        <img src="{{ suggested_user.avatar_url }}" style="width: 32px; height: 32px;" class="rounded-circle"/>
    </div>
    <div class="">
        <a href="{% url 'instagramsns:user_page' suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ml-auto">
        <a href="{% url 'user_follow' suggested_user.username %}">
            <span class="text-primary font-weight-bold">Follow</span>
        </a>
        <a href="{% url 'user_unfollow' suggested_user.username %}">
            <span class="text-primary font-weight-bold">Unfollow</span>
        </a>
    </div>
</div> 

instagramsns/templates/instagramsns/user_page.html
{% extends "instagramsns/layout.html" %}
{% load thumbnail %}

{% block content %}

    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.avatar_url }}" class="rounded-circle" style="width: 160px; height: 160px;" />
            </div>

            <div class="col-sm-9 mt-1">
                <div class="d-flex flex-row">
                    <div class="p-2">
                          <!--user.username 은 현재 로그인한 유저를 나타낸다.-->
                        <span style="font-size: 1.3rem; font-weight: bold;">{{ page_user.username }}</span> 
                    </div>
                    <div class="p-2">
                        <a href="{% url 'profile_edit' %}" class="btn btn-outline-dark btn-sm">
                            Edit Profile
                        </a>

                        {% if is_follow %}
                            <a href="{% url 'user_unfollow' page_user.username %}" class="btn btn-outline-primary btn-sm">
                                Unfollow
                            </a>
                        {% else %}
                            <a href="{% url 'user_follow' page_user.username %}" class="btn btn-outline-primary btn-sm">
                                Follow
                            </a>
                        {% endif %}
                    </div>
                </div>
           
                <div class="d-flex flex-row">
                    <div class="p-2">
                        <span style="font-size: 1.1rem; font-weight: bold;">{{ post_list_count }}</span> posts
                    </div>
                    <div class="p-2">
                        <span style="font-size: 1.1rem; font-weight: bold;">0</span> fllowers
                    </div>
                    <div class="p-2">
                        <span style="font-size: 1.1rem; font-weight: bold;">0</span> following
                    </div>
                </div>
                
                <div class="d-flex flex-row">
                    <div class="p-2">{{ page_user.username }}</div>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            {% for post in post_list %}
                <div class="col-sm-3 mb-3">
                    <img src="{% thumbnail post.photo 300x300 crop %}" alt="{{ post.caption }}" style="width: 100%; height: 100%;" />
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}